### ISSUE TITLE
Undefined variable: where_cache

### ISSUE THREAD

**Issue by Kristories** [sepehr/ci-mongodb-base-model#1]
Hi,

Update `_count()` function

https://github.com/Kristories/ci-mongodb-base-model/commit/bd910f9009d8539838589b79437af1670e82f9bf

**Comment by sepehr** [comment]
Thanks for the catch, 

I'm aware of the issue (and a few more), I updated the model in my local working project but couldn't find the time to update this repo as well.

Thank you.
